// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `call_state`, `call_state`, `get_contact`, `get_contact`, `get_contacts`, `get_contacts`, `manager_active`, `manager_active`, `message_received`, `message_received`, `post`, `post`, `screenshare_started`, `screenshare_started`, `session_status`, `session_status`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Notify >>>
abstract class ArcNotify implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JoinHandle < bool >>>
abstract class JoinHandleBool implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<S>>
abstract class S implements RustOpaqueInterface {}

abstract class Callbacks {
  Future<JoinHandleBool> getAcceptHandle(
      {required String contactId,
      Uint8List? ringtone,
      required ArcNotify cancel});

  Future<S> statisticsCallback();
}
