// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'audio/player.dart';
import 'error.dart';
import 'flutter.dart';
import 'frb_generated.dart';
import 'overlay/overlay.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `codec_config`, `latencies_missing`, `loopback`, `new`, `new`, `new`, `new`, `open_stream`, `receive_stream`, `relayed_only`, `statistics_collector`, `stream_to_audio_transport`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectionState`, `EarlyCallState`, `OptionalCallArgs`, `PeerState`, `RoomConnection`, `RoomMessage`, `RoomState`, `SessionState`, `StartScreenshare`, `StatisticsCollectorState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Telepathy>>
abstract class Telepathy implements RustOpaqueInterface {
  /// Blocks while an audio test is running
  Future<void> audioTest();

  ChatMessage buildChat(
      {required Contact contact,
      required String text,
      required List<(String, Uint8List)> attachments});

  /// Ends the current audio test, room, or call in that order
  Future<void> endCall();

  /// The only entry point into participating in a room
  Future<void> joinRoom({required List<String> memberStrings});

  /// Lists the input and output devices
  Future<(List<String>, List<String>)> listDevices();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Telepathy> newInstance(
          {required List<int> identity,
          required ArcHost host,
          required NetworkConfig networkConfig,
          required ScreenshareConfig screenshareConfig,
          required Overlay overlay,
          required CodecConfig codecConfig,
          required FlutterCallbacks callbacks}) =>
      RustLib.instance.api.crateTelepathyTelepathyNew(
          identity: identity,
          host: host,
          networkConfig: networkConfig,
          screenshareConfig: screenshareConfig,
          overlay: overlay,
          codecConfig: codecConfig,
          callbacks: callbacks);

  /// Restarts the session manager
  Future<void> restartManager();

  /// Sends a chat message
  Future<void> sendChat({required ChatMessage message});

  void setDeafened({required bool deafened});

  /// Changing the denoise flag will not affect the current call
  void setDenoise({required bool denoise});

  void setEfficiencyMode({required bool enabled});

  /// Sets the signing key (called when the profile changes)
  Future<void> setIdentity({required List<int> key});

  Future<void> setInputDevice({String? device});

  void setInputVolume({required double decibel});

  Future<void> setModel({Uint8List? model});

  void setMuted({required bool muted});

  Future<void> setOutputDevice({String? device});

  void setOutputVolume({required double decibel});

  void setPlayCustomRingtones({required bool play});

  void setRmsThreshold({required double decimal});

  void setSendCustomRingtone({required bool send});

  /// Attempts to start a call through an existing session
  Future<void> startCall({required Contact contact});

  Future<void> startScreenshare({required Contact contact});

  /// Tries to start a session for a contact
  Future<void> startSession({required Contact contact});

  /// Stops a specific session (called when a contact is deleted)
  Future<void> stopSession({required Contact contact});
}
