// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decoders`, `devices`, `encoder_from_str`, `make_command`, `make_command`, `new`, `parse_codecs`, `playback`, `record`, `test_config`, `to_args`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Decoder`, `Device`, `Encoder`, `PlaybackConfig`, `ScreenshareConfigDisk`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from_str`, `from_str`, `from_str`, `from`, `from`, `from`, `minimum_bytes_needed`, `minimum_bytes_needed`, `minimum_bytes_needed`, `minimum_bytes_needed`, `read_from`, `read_from`, `read_from`, `read_from`, `speedy_convert_slice_endianness`, `speedy_flip_endianness`, `speedy_is_primitive`, `speedy_is_primitive`, `speedy_slice_as_bytes`, `speedy_slice_from_bytes`, `write_to`, `write_to`, `write_to`, `write_to`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Capabilities>>
abstract class Capabilities implements RustOpaqueInterface {
  static Future<Capabilities> default_() =>
      RustLib.instance.api.crateInternalScreenshareCapabilitiesDefault();

  List<String> devices();

  List<String> encoders();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecordingConfig>>
abstract class RecordingConfig implements RustOpaqueInterface {
  int bitrate();

  String device();

  String encoder();

  int framerate();

  int? height();
}
