// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Loads a ringtone from a WAV file and converts it to SEA format.
///
/// This function reads a WAV file, encodes it to the SEA codec format,
/// and saves it as "ringtone.sea" for efficient playback.
///
/// # Arguments
///
/// * `path` - Path to the WAV file to convert.
///
/// # Platform Support
///
/// - **Native**: Performs the file I/O and encoding.
/// - **WASM**: No-op (returns Ok immediately).
Future<void> loadRingtone({required String path}) =>
    RustLib.instance.api.crateAudioPlayerLoadRingtone(path: path);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Host >>>
abstract class ArcHost implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterSoundHandle>>
abstract class FlutterSoundHandle implements RustOpaqueInterface {
  /// Cancels the sound playback.
  ///
  /// This triggers a graceful fade-out to prevent audio pops/clicks.
  void cancel();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SoundPlayer>>
abstract class SoundPlayer implements RustOpaqueInterface {
  /// Returns a reference to the audio host.
  ///
  /// This can be used to enumerate devices or access other host functionality.
  ArcHost host();

  /// Creates a new sound player with the specified output volume.
  ///
  /// # Arguments
  ///
  /// * `output_volume` - Output volume in decibels. 0 dB is unity gain,
  ///   negative values attenuate, positive values amplify.
  factory SoundPlayer({required double outputVolume}) => RustLib.instance.api
      .crateAudioPlayerSoundPlayerNew(outputVolume: outputVolume);

  /// Plays audio from the provided bytes.
  ///
  /// Supports both WAV files (with standard 44-byte header) and SEA codec files.
  /// The format is auto-detected based on header validation.
  ///
  /// # Arguments
  ///
  /// * `bytes` - The audio file bytes (WAV or SEA format).
  ///
  /// # Returns
  ///
  /// A `FlutterSoundHandle` that can be used to cancel playback.
  Future<FlutterSoundHandle> play({required List<int> bytes});

  /// Sets the output device.
  ///
  /// # Arguments
  ///
  /// * `device_id` - The device ID string to use, or `None` for the default device.
  Future<void> updateOutputDevice({String? deviceId});

  /// Updates the output volume.
  ///
  /// # Arguments
  ///
  /// * `volume` - New volume in decibels.
  void updateOutputVolume({required double volume});
}
