// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'overlay.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'player.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `invoke`, `notify`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FlutterStatisticsCallback`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterCallbacks>>
abstract class FlutterCallbacks implements RustOpaqueInterface {
  factory FlutterCallbacks(
          {required FutureOr<bool> Function(
                  (String, Uint8List?, FrontendNotify))
              acceptCall,
          required FutureOr<Contact?> Function(Uint8List) getContact,
          required FutureOr<void> Function(CallState) callState,
          required FutureOr<void> Function((String, SessionStatus))
              sessionStatus,
          required FutureOr<List<Contact>> Function(void) getContacts,
          required FutureOr<void> Function(Statistics) statistics,
          required FutureOr<void> Function(ChatMessage) messageReceived,
          required FutureOr<void> Function(ManagerState) managerActive,
          required FutureOr<void> Function((FrontendNotify, bool))
              screenshareStarted}) =>
      RustLib.instance.api.crateFlutterFlutterCallbacksNew(
          acceptCall: acceptCall,
          getContact: getContact,
          callState: callState,
          sessionStatus: sessionStatus,
          getContacts: getContacts,
          statistics: statistics,
          messageReceived: messageReceived,
          managerActive: managerActive,
          screenshareStarted: screenshareStarted);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StartOperation>>
abstract class StartOperation implements RustOpaqueInterface {
  void cancel();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Telepathy>>
abstract class Telepathy implements RustOpaqueInterface {
  /// Blocks while an audio test is running
  Future<void> audioTest();

  /// Phase one of the two-phase identity-switch transaction.
  ///
  /// Validates the target payload, acquires the backend call slot in the
  /// `IdentitySwitch` gate so no call/room/audio-test can begin while the
  /// frontend mutates its active profile, and stashes the validated
  /// target so the parameterless [`commit_identity_switch`](Self::commit_identity_switch)
  /// can apply it. The frontend MUST follow this with exactly one of
  /// `commit_identity_switch` or [`cancel_identity_switch`](Self::cancel_identity_switch).
  ///
  /// Validating the target key length HERE — before the slot is reserved —
  /// guarantees a malformed payload returns an error without wedging the
  /// slot. The frontend must call `cancel_identity_switch` BEFORE mutating
  /// Rust when its own persistence between this call and `commit` fails.
  Future<void> beginIdentitySwitch(
      {required List<int> targetKey, required List<Contact> targetContacts});

  ChatMessage buildChat(
      {required Contact contact,
      required String text,
      required List<(String, Uint8List)> attachments});

  /// Phase two cancel of the two-phase identity-switch transaction.
  ///
  /// Releases the `IdentitySwitch` gate without mutating the signing
  /// identity. The frontend must call this when its own persistence failed
  /// between [`begin_identity_switch`](Self::begin_identity_switch) and
  /// [`commit_identity_switch`](Self::commit_identity_switch).
  Future<void> cancelIdentitySwitch();

  /// Phase two commit of the two-phase identity-switch transaction.
  ///
  /// Applies the target identity + contact snapshot validated and stashed
  /// by [`begin_identity_switch`](Self::begin_identity_switch), restarts
  /// the session manager, and rehydrates sessions for that snapshot.
  ///
  /// On any failure after the identity has been mutated, the backend
  /// restores the previous identity and session set captured at
  /// `begin_identity_switch` before releasing the gate. The frontend must
  /// roll back its own active-profile persistence when this returns an
  /// error.
  Future<void> commitIdentitySwitch();

  /// Ends the current audio test, room, or call in that order
  Future<void> endCall();

  /// The only entry point into participating in a room.
  Future<void> joinRoom(
      {required List<String> memberStrings, required StartOperation operation});

  /// Lists the input and output devices
  Future<(List<AudioDevice>, List<AudioDevice>)> listDevices();

  factory Telepathy(
          {required ArcHost host,
          required NetworkConfig networkConfig,
          required ScreenshareConfig screenshareConfig,
          required Overlay overlay,
          required CodecConfig codecConfig,
          required FlutterCallbacks callbacks}) =>
      RustLib.instance.api.crateFlutterTelepathyNew(
          host: host,
          networkConfig: networkConfig,
          screenshareConfig: screenshareConfig,
          overlay: overlay,
          codecConfig: codecConfig,
          callbacks: callbacks);

  /// Creates an operation token that can cancel one pending call or room start.
  StartOperation newStartOperation();

  void pauseStatistics();

  /// Retries restoring the identity and contacts retained after a failed rollback.
  Future<void> recoverIdentitySwitch();

  /// Restarts the session manager
  Future<void> restartManager();

  void resumeStatistics();

  /// Sends a chat message
  Future<void> sendChat({required ChatMessage message});

  void setContactOutputVolume({required Contact contact});

  void setDeafened({required bool deafened});

  /// Denoise is set on the processor; the current call is not reconfigured.
  void setDenoise({required bool denoise});

  void setEfficiencyMode({required bool enabled});

  /// Sets the signing key (called when the profile changes)
  Future<void> setIdentity({required List<int> key});

  Future<void> setInputDevice({String? deviceId});

  void setInputVolume({required double decibel});

  Future<void> setModel({Uint8List? model});

  void setMuted({required bool muted});

  Future<void> setOutputDevice({String? deviceId});

  void setOutputVolume({required double decibel});

  void setPlayCustomRingtones({required bool play});

  void setRmsThreshold({required double decimal});

  void setSendCustomRingtone({required bool send});

  /// shuts down the entire rust backend
  Future<void> shutdown();

  /// Attempts to start a call through an existing session.
  Future<void> startCall(
      {required Contact contact, required StartOperation operation});

  Future<void> startManager();

  Future<void> startScreenshare({required Contact contact});

  /// Tries to start a session for a contact
  Future<void> startSession({required Contact contact});

  /// Stops a specific session (called when a contact is deleted)
  Future<void> stopSession({required Contact contact});
}
