// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'overlay.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'player.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `invoke`, `notify`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FlutterStatisticsCallback`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterCallbacks>>
abstract class FlutterCallbacks implements RustOpaqueInterface {
  factory FlutterCallbacks(
          {required FutureOr<bool> Function(
                  (String, Uint8List?, FrontendNotify))
              acceptCall,
          required FutureOr<Contact?> Function(Uint8List) getContact,
          required FutureOr<void> Function(CallState) callState,
          required FutureOr<void> Function((String, SessionStatus))
              sessionStatus,
          required FutureOr<List<Contact>> Function(void) getContacts,
          required FutureOr<void> Function(Statistics) statistics,
          required FutureOr<void> Function(ChatMessage) messageReceived,
          required FutureOr<void> Function(ManagerState) managerActive,
          required FutureOr<void> Function((FrontendNotify, bool))
              screenshareStarted}) =>
      RustLib.instance.api.crateFlutterFlutterCallbacksNew(
          acceptCall: acceptCall,
          getContact: getContact,
          callState: callState,
          sessionStatus: sessionStatus,
          getContacts: getContacts,
          statistics: statistics,
          messageReceived: messageReceived,
          managerActive: managerActive,
          screenshareStarted: screenshareStarted);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StartOperation>>
abstract class StartOperation implements RustOpaqueInterface {
  void cancel();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Telepathy>>
abstract class Telepathy implements RustOpaqueInterface {
  /// Blocks while an audio test is running
  Future<void> audioTest();

  ChatMessage buildChat(
      {required Contact contact,
      required String text,
      required List<(String, Uint8List)> attachments});

  /// Ends the current audio test, room, or call in that order
  Future<void> endCall();

  /// The only entry point into participating in a room.
  Future<void> joinRoom(
      {required List<String> memberStrings, required StartOperation operation});

  /// Lists the input and output devices
  Future<(List<AudioDevice>, List<AudioDevice>)> listDevices();

  factory Telepathy(
          {required ArcHost host,
          required NetworkConfig networkConfig,
          required ScreenshareConfig screenshareConfig,
          required Overlay overlay,
          required CodecConfig codecConfig,
          required FlutterCallbacks callbacks}) =>
      RustLib.instance.api.crateFlutterTelepathyNew(
          host: host,
          networkConfig: networkConfig,
          screenshareConfig: screenshareConfig,
          overlay: overlay,
          codecConfig: codecConfig,
          callbacks: callbacks);

  /// Creates an operation token that can cancel one pending call or room start.
  StartOperation newStartOperation();

  void pauseStatistics();

  /// Restarts the session manager without changing the signing identity.
  ///
  /// Use this when only the manager needs recycling (e.g. network-config
  /// save, manual recovery button). For profile switches use
  /// [switchIdentityAndRestartManager] instead — the separate
  /// `set_identity` + `restart_manager` sequence races `start_call`
  /// between validation and identity mutation.
  Future<void> restartManager();

  void resumeStatistics();

  /// Sends a chat message
  Future<void> sendChat({required ChatMessage message});

  void setContactOutputVolume({required Contact contact});

  void setDeafened({required bool deafened});

  /// Denoise is set on the processor; the current call is not reconfigured.
  void setDenoise({required bool denoise});

  void setEfficiencyMode({required bool enabled});

  /// Sets the signing key without restarting the manager.
  ///
  /// Intended for the bootstrap path before the manager is running. For
  /// any post-startup identity change use [switchIdentityAndRestartManager]
  /// instead — the atomic op holds the call slot across mutation and
  /// restart, which the separate calls cannot do.
  Future<void> setIdentity({required List<int> key});

  Future<void> setInputDevice({String? deviceId});

  void setInputVolume({required double decibel});

  Future<void> setModel({Uint8List? model});

  void setMuted({required bool muted});

  Future<void> setOutputDevice({String? deviceId});

  void setOutputVolume({required double decibel});

  void setPlayCustomRingtones({required bool play});

  void setRmsThreshold({required double decimal});

  void setSendCustomRingtone({required bool send});

  /// shuts down the entire rust backend
  Future<void> shutdown();

  /// Attempts to start a call through an existing session.
  Future<void> startCall(
      {required Contact contact, required StartOperation operation});

  Future<void> startManager();

  Future<void> startScreenshare({required Contact contact});

  /// Tries to start a session for a contact
  Future<void> startSession({required Contact contact});

  /// Stops a specific session (called when a contact is deleted)
  Future<void> stopSession({required Contact contact});

  /// Atomically swaps the signing identity and restarts the session manager
  /// while reserving the call slot, so a call cannot start between
  /// validation, identity mutation, and manager restart. This is the
  /// transactional path frontend profile switches must use instead of
  /// separate `set_identity` + `restart_manager` calls.
  Future<void> switchIdentityAndRestartManager({required List<int> key});
}
