// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `clamp_contact_output_volume`, `contact_output_volume_from_parts`, `contact_output_volume_in_range`, `field_error`, `new`, `parse_bind_addresses`, `poison_field_error`, `relay_map_from_urls`, `serialize_timestamp_rfc3339_utc`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `minimum_bytes_needed`, `read_from`, `write_to`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Capabilities>>
abstract class Capabilities implements RustOpaqueInterface {
  static Future<Capabilities> default_() =>
      RustLib.instance.api.crateTypesCapabilitiesDefault();

  List<String> devices();

  List<String> encoders();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChatMessage>>
abstract class ChatMessage implements RustOpaqueInterface {
  List<(String, Uint8List)> attachments();

  PublicKey get receiver;

  String get text;

  set receiver(PublicKey receiver);

  set text(String text);

  void clearAttachments();

  bool isSender({required String identity});

  String time();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CodecConfig>>
abstract class CodecConfig implements RustOpaqueInterface {
  static Future<CodecConfig> default_() =>
      RustLib.instance.api.crateTypesCodecConfigDefault();

  factory CodecConfig(
          {required bool enabled,
          required bool vbr,
          required double residualBits}) =>
      RustLib.instance.api.crateTypesCodecConfigNew(
          enabled: enabled, vbr: vbr, residualBits: residualBits);

  void setEnabled({required bool enabled});

  void setResidualBits({required double residualBits});

  void setVbr({required bool vbr});

  (bool, bool, double) toValues();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Contact>>
abstract class Contact implements RustOpaqueInterface {
  static Contact fromParts(
          {required String id,
          required String nickname,
          required String peerId,
          required double outputVolume}) =>
      RustLib.instance.api.crateTypesContactFromParts(
          id: id,
          nickname: nickname,
          peerId: peerId,
          outputVolume: outputVolume);

  Future<PublicKey> getPeerId();

  String id();

  bool idEq({required List<int> id});

  factory Contact({required String nickname, required String peerId}) =>
      RustLib.instance.api
          .crateTypesContactNew(nickname: nickname, peerId: peerId);

  String nickname();

  double outputVolume();

  String peerId();

  Contact pubClone();

  void setNickname({required String nickname});

  void setOutputVolume({required double decibel});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrontendNotify>>
abstract class FrontendNotify implements RustOpaqueInterface {
  /// public notified function for dart
  Future<void> notified();

  /// notifies one waiter
  void notify();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NetworkConfig>>
abstract class NetworkConfig implements RustOpaqueInterface {
  static Future<NetworkConfig> default_() =>
      RustLib.instance.api.crateTypesNetworkConfigDefault();

  List<String> getBindAddresses();

  String? getDnsEndpoint();

  String? getDnsOriginDomain();

  int getListenPort();

  String? getPkarrRelay();

  List<String>? getRelays();

  factory NetworkConfig(
          {required int listenPort,
          required List<String> bindAddresses,
          List<String>? relays,
          String? dnsEndpoint,
          String? dnsOriginDomain,
          String? pkarrRelay}) =>
      RustLib.instance.api.crateTypesNetworkConfigNew(
          listenPort: listenPort,
          bindAddresses: bindAddresses,
          relays: relays,
          dnsEndpoint: dnsEndpoint,
          dnsOriginDomain: dnsOriginDomain,
          pkarrRelay: pkarrRelay);

  /// Atomically validate every field and apply the new configuration.
  ///
  /// Each field is parsed and validated up front (without mutating any
  /// shared state) before any write is attempted. If validation fails
  /// for any field, no writes occur and the live `NetworkConfig` is
  /// left exactly as it was. This is the only safe way for callers to
  /// update a multi-field configuration: the per-field setters above
  /// can leave the live config partially mutated if a later setter
  /// rejects its value.
  ///
  /// On failure the returned [`NetworkConfigUpdateError`] identifies
  /// which field was rejected so the frontend can route the error to
  /// the correct input. A poisoned lock is collapsed into
  /// [`NetworkConfigField::BackendError`]: a poison indicates the rust
  /// runtime has been corrupted by a panic, and attributing that to
  /// any one user-supplied field would be misleading.
  void update(
      {required int listenPort,
      required List<String> bindAddresses,
      List<String>? relays,
      String? dnsEndpoint,
      String? dnsOriginDomain,
      String? pkarrRelay});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecordingConfig>>
abstract class RecordingConfig implements RustOpaqueInterface {
  int bitrate();

  String device();

  String encoder();

  int framerate();

  int? height();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ScreenshareConfig>>
abstract class ScreenshareConfig implements RustOpaqueInterface {
  Future<Capabilities> capabilities();

  static Future<ScreenshareConfig> default_() =>
      RustLib.instance.api.crateTypesScreenshareConfigDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ScreenshareConfig> newInstance({required List<int> buffer}) =>
      RustLib.instance.api.crateTypesScreenshareConfigNew(buffer: buffer);

  Future<RecordingConfig?> recordingConfig();

  Uint8List toBytes();

  Future<void> updateRecordingConfig(
      {required String encoder,
      required String device,
      required int bitrate,
      required int framerate,
      int? height});
}

@freezed
sealed class CallState with _$CallState {
  const CallState._();

  const factory CallState.connected() = CallState_Connected;
  const factory CallState.waiting() = CallState_Waiting;
  const factory CallState.roomJoin(
    String field0,
  ) = CallState_RoomJoin;
  const factory CallState.roomLeave(
    String field0,
  ) = CallState_RoomLeave;
  const factory CallState.callEnded(
    String field0,
    bool field1,
  ) = CallState_CallEnded;
}

class DartError implements FrbException {
  final String message;

  const DartError({
    required this.message,
  });

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

enum ManagerState {
  stopped,
  starting,
  active,
  failed,
  ;
}

/// Identifies which field of a [`NetworkConfig`] update failed validation,
/// or that the failure was not tied to a specific user-supplied field.
///
/// `update` validates every field before mutating any shared state, and
/// reports the first failure. Surfacing the offending field through this
/// enum (rather than only a free-form message) lets the frontend route the
/// error to the corresponding input.
enum NetworkConfigField {
  /// The supplied listen port is not representable as a `u16`. The
  /// rust setter takes `u16` so the frontend validator should already
  /// have caught this, but the variant is kept for completeness in
  /// case a future caller bypasses validation.
  listenPort,

  /// One or more bind addresses failed to parse as an `IpAddr`.
  bindAddresses,

  /// One or more relay URLs failed to parse as a [`RelayUrl`].
  relays,

  /// The DNS endpoint failed to parse as a [`SocketAddr`].
  dnsEndpoint,

  /// The DNS origin domain is invalid. The current rust setter does
  /// not validate the origin domain itself, but the variant is
  /// reserved for future tightening and lets the frontend surface a
  /// targeted error rather than a generic message.
  dnsOriginDomain,

  /// The Pkarr relay URL failed to parse as a [`url::Url`].
  pkarrRelay,

  /// The failure was not tied to a specific field. In particular,
  /// every lock-poison error from the atomic `update` is collapsed
  /// into this variant: a poisoned lock indicates the rust runtime
  /// has been corrupted by a panic, and attributing the error to any
  /// one user-supplied field would be misleading. Frontends should
  /// surface this as a critical "backend error" rather than a
  /// per-field validation message.
  backendError,
  ;
}

/// Structured error returned by [`NetworkConfig::update`].
///
/// Carries both the offending [`NetworkConfigField`] (so the frontend
/// can route the error to the correct input) and the underlying
/// message (so the user sees the rust-side diagnostic verbatim).
class NetworkConfigUpdateError implements FrbException {
  final NetworkConfigField field;
  final String message;

  const NetworkConfigUpdateError({
    required this.field,
    required this.message,
  });

  @override
  int get hashCode => field.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkConfigUpdateError &&
          runtimeType == other.runtimeType &&
          field == other.field &&
          message == other.message;
}

@freezed
sealed class SessionStatus with _$SessionStatus {
  const SessionStatus._();

  const factory SessionStatus.connecting() = SessionStatus_Connecting;
  const factory SessionStatus.connected({
    required bool relayed,
    required String remoteAddress,
  }) = SessionStatus_Connected;
  const factory SessionStatus.inactive() = SessionStatus_Inactive;
  const factory SessionStatus.unknown() = SessionStatus_Unknown;
}

/// processed statistics for the frontend
class Statistics {
  /// a percentage of the max input volume in the window
  final double inputLevel;

  /// a percentage of the max output volume in the window
  final double outputLevel;

  /// the current call latency
  final BigInt latency;

  /// the approximate upload bandwidth used by the current call
  final BigInt uploadBandwidth;

  /// the approximate download bandwidth used by the current call
  final BigInt downloadBandwidth;

  /// the number of output samples that were lost in the interval
  final BigInt loss;

  const Statistics({
    required this.inputLevel,
    required this.outputLevel,
    required this.latency,
    required this.uploadBandwidth,
    required this.downloadBandwidth,
    required this.loss,
  });

  static Future<Statistics> default_() =>
      RustLib.instance.api.crateTypesStatisticsDefault();

  @override
  int get hashCode =>
      inputLevel.hashCode ^
      outputLevel.hashCode ^
      latency.hashCode ^
      uploadBandwidth.hashCode ^
      downloadBandwidth.hashCode ^
      loss.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Statistics &&
          runtimeType == other.runtimeType &&
          inputLevel == other.inputLevel &&
          outputLevel == other.outputLevel &&
          latency == other.latency &&
          uploadBandwidth == other.uploadBandwidth &&
          downloadBandwidth == other.downloadBandwidth &&
          loss == other.loss;
}
