// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(String, Uint8List) generateKeys() =>
    RustLib.instance.api.crateFlutterUtilsGenerateKeys();

String roomHash({required List<String> peers}) =>
    RustLib.instance.api.crateFlutterUtilsRoomHash(peers: peers);

bool validatePeerId({required String peerId}) =>
    RustLib.instance.api.crateFlutterUtilsValidatePeerId(peerId: peerId);

Future<bool> screenshareAvailable() =>
    RustLib.instance.api.crateFlutterUtilsScreenshareAvailable();
